spring:
  cloud:
    config:
      discovery:
        enabled: true
        service-id: cloud-config
  datasource:
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://mysql:3306/codeforfun?useUnicode=true&useSSL=false&autoReconnect=true&createDatabaseIfNotExist=true
    type: com.mchange.v2.c3p0.ComboPooledDataSource
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57InnoDBDialect