zuul:
  prefix: /api
  routes:
    cloud-user:
      path: /cloud-user/**
      service-id: cloud-user
      name: 用户模块
      version: 1.0
    cloud-wechat:
      path: /cloud-wechat/**
      service-id: cloud-wechat
      name: 微信模块
      version: 1.0
  add-proxy-headers: true
spring:
  datasource:
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://mysql:3306/codeforfun?useUnicode=true&useSSL=false&autoReconnect=true&createDatabaseIfNotExist=true
    type: com.alibaba.druid.pool.DruidDataSource
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57InnoDBDialect