version: "3"
services:
#  cloud-nginx:
#    build: cloud-nginx
#    image: registry.cn-beijing.aliyuncs.com/wangdali/cloud-nginx
#    restart: always
#    ports: ["80:80"]
#    environment:
#      - "TZ=Asia/Shanghai"
#  cloud-front:
#    build: cloud-front
#    image: registry.cn-beijing.aliyuncs.com/wangdali/cloud-front
#    restart: always
#    volumes:
#      - "./cloud-front/static:/app"
#    environment:
#      - "TZ=Asia/Shanghai"
  cloud-eureka:
    build: cloud-eureka
    image: registry.cn-beijing.aliyuncs.com/wangdali/cloud-eureka
    environment:
      - "TZ=Asia/Shanghai"
    ports:
      - "8761:8761"
  cloud-config:
    build: cloud-config
    image: registry.cn-beijing.aliyuncs.com/wangdali/cloud-config
    environment:
      - "TZ=Asia/Shanghai"
    ports:
      - "8000:8000"
    depends_on:
      - cloud-eureka
  cloud-gateway:
    build: cloud-gateway
    image: registry.cn-beijing.aliyuncs.com/wangdali/cloud-gateway
    environment:
      - "TZ=Asia/Shanghai"
    ports:
      - "8888:8888"
    depends_on:
      - cloud-eureka
  cloud-hystrix:
    build: cloud-hystrix
    image: registry.cn-beijing.aliyuncs.com/wangdali/cloud-hystrix
    environment:
      - "TZ=Asia/Shanghai"
    depends_on:
      - cloud-eureka
    ports:
      - "8300:8300"
  cloud-turbine:
    build: cloud-turbine
    image: registry.cn-beijing.aliyuncs.com/wangdali/cloud-turbine
    environment:
      - "TZ=Asia/Shanghai"
    ports:
      - "8400:8400"
    depends_on:
      - cloud-eureka
  cloud-user:
    build: cloud-user
    image: registry.cn-beijing.aliyuncs.com/wangdali/cloud-user
    environment:
      - "TZ=Asia/Shanghai"
    depends_on:
      - cloud-config
      - cloud-gateway
      - mysql
  cloud-wechat:
    build: cloud-wechat
    image: registry.cn-beijing.aliyuncs.com/wangdali/cloud-wechat
    environment:
      - "TZ=Asia/Shanghai"
    depends_on:
      - cloud-config
      - cloud-gateway
  mysql: #mysql数据库
    image: mysql:5.7.19
    hostname: mysql
    volumes: # 挂载 下边每行前边的`-`代表这个东西是数组的一个元素.就是说volumes属性的值是一个数组
      - "./docker/mysql/data:/var/lib/mysql" # mysql数据文件位置
      - "./docker/mysql/conf:/etc/mysql/conf.d" # mysql配置文件位置
    restart: always # 容器重启策略
    environment:
      MYSQL_ROOT_PASSWORD: root
    environment:
      - "TZ=Asia/Shanghai"
    ports:
      - "3306:3306"
volumes:
  maven: