version: "3"
services:
  cloud-nginx:
    build: cloud-nginx
    image: registry.cn-beijing.aliyuncs.com/wangdali/cloud-nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    environment:
      TZ: Asia/Shanghai
  cloud-eureka:
    image: registry.cn-beijing.aliyuncs.com/wangdali/cloud-eureka
    environment:
      TZ: Asia/Shanghai
  cloud-config:
    image: registry.cn-beijing.aliyuncs.com/wangdali/cloud-config
    environment:
      TZ: Asia/Shanghai
    depends_on:
      - cloud-eureka
  cloud-gateway:
    image: registry.cn-beijing.aliyuncs.com/wangdali/cloud-gateway
    environment:
      TZ: Asia/Shanghai
    depends_on:
      - cloud-eureka
  cloud-user:
    image: registry.cn-beijing.aliyuncs.com/wangdali/cloud-user
    environment:
      TZ: Asia/Shanghai
    depends_on:
      - cloud-gateway
      - cloud-config
      - mysql
  cloud-wechat:
    image: registry.cn-beijing.aliyuncs.com/wangdali/cloud-wechat
    environment:
      TZ: Asia/Shanghai
    depends_on:
      - cloud-gateway
      - cloud-config
  mysql: #mysql数据库
    image: mysql:5.7.19
    hostname: mysql
    volumes: # 挂载 下边每行前边的`-`代表这个东西是数组的一个元素.就是说volumes属性的值是一个数组
      - "./docker/mysql/data:/var/lib/mysql" # mysql数据文件位置
      - "./docker/mysql/conf:/etc/mysql/conf.d" # mysql配置文件位置
    restart: always # 容器重启策略
    environment:
      MYSQL_ROOT_PASSWORD: root
      TZ: Asia/Shanghai
  ngrok:
    image: hteen/ngrok
    ports:
      - "4443:4443"
    environment:
      DOMAIN: ngrok.codeforfun.cn
      TZ: Asia/Shanghai
    command: /bin/sh /server.sh
    volumes:
      - "/data/ngrok:/myfiles"
  jenkins:
    image: jenkins/jenkins
    environment:
      TZ: Asia/Shanghai
    user: root
    volumes:
      - "./docker/jenkins/data:/var/jenkins_home"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "$(which docker):/usr/bin/docker"
  redmine:
    image: redmine
    restart: always
    environment:
      REDMINE_DB_MYSQL: db # 数据库服务名，对应11行的db:
      REDMINE_DB_PASSWORD: example # 数据库密码
      TZ: Asia/Shanghai
  db:
    image: mysql:5.7 # mysql镜像版本
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example # 数据库初始密码
      MYSQL_DATABASE: redmine # 数据库名，自动生成库
      TZ: Asia/Shanghai # 时区(timezone)，防止美国时间
    volumes:
      - "~/docker/redmine/mysql_data:/var/lib/mysql" # ./mysql/data数据库在本地的存放位置(可以修改)
      - "./docker/mysql/conf/my.cnf:/etc/mysql/conf.d/my.cnf" # mysql配置文件，可自行修改
volumes:
  maven: