version: "3"
services:
  cloud-nginx:
    build: cloud-nginx
    image: registry.cn-beijing.aliyuncs.com/wangdali/cloud-nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
  cloud-eureka:
    image: registry.cn-beijing.aliyuncs.com/wangdali/cloud-eureka
    environment:
      - "TZ=Asia/Shanghai"
  cloud-config:
    image: registry.cn-beijing.aliyuncs.com/wangdali/cloud-config
    environment:
      - "TZ=Asia/Shanghai"
    depends_on:
      - cloud-eureka
  cloud-gateway:
    image: registry.cn-beijing.aliyuncs.com/wangdali/cloud-gateway
    environment:
      - "TZ=Asia/Shanghai"
    depends_on:
      - cloud-eureka
  cloud-user:
    image: registry.cn-beijing.aliyuncs.com/wangdali/cloud-user
    environment:
      - "TZ=Asia/Shanghai"
    depends_on:
      - cloud-gateway
      - cloud-config
      - mysql
  cloud-wechat:
    image: registry.cn-beijing.aliyuncs.com/wangdali/cloud-wechat
    environment:
      - "TZ=Asia/Shanghai"
    depends_on:
      - cloud-gateway
      - cloud-config
  mysql: #mysql数据库
    image: mysql:5.7.19
    hostname: mysql
    volumes: # 挂载 下边每行前边的`-`代表这个东西是数组的一个元素.就是说volumes属性的值是一个数组
      - "./docker/mysql/data:/var/lib/mysql" # mysql数据文件位置
      - "./docker/mysql/conf:/etc/mysql/conf.d" # mysql配置文件位置
    restart: always # 容器重启策略
    environment:
      MYSQL_ROOT_PASSWORD: root
    environment:
      - "TZ=Asia/Shanghai"
  ngrok:
    image: hteen/ngrok
    ports:
      - "4443:4443"
    environment:
      DOMAIN: ngrok.codeforfun.cn
    command: /bin/sh /server.sh
    volumes:
      - "/data/ngrok:/myfiles"
  redmine:
    image: sameersbn/redmine:3.4.2
    volumes:
      - "~/docker/redmine/mysql_data:/var/lib/mysql"
      - "~/docker/redmine/redmine_data:/home/redmine/data"
    environment:
      - TZ=Asia/Shanghai
volumes:
  maven: