server:
  port: 8761
spring:
  application:
    name: cloud-eureka
eureka:
  client:
    service-url:
      defauleZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  instance:
    hostname: cloud-eureka