server:
  port: 8110
spring:
  datasource:
    url: jdbc:mysql:///codeforfun?useUnicode=true&useSSL=false&autoReconnect=true&createDatabaseIfNotExist=true
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    initialize: false
  application:
    name: cloud-oauth
eureka:
  client:
    service-url:
      defaultZone: http://cloud-eureka:8761/eureka/
  instance:
    hostname: cloud-oauth