server:
  port: 8080
spring:
  application:
    name: cloud-wechat
  thymeleaf:
    cache: false
  rabbitmq:
    username: admin
    password: admin
eureka:
  client:
    service-url:
      defaultZone: http://cloud-eureka:8761/eureka/
feign:
  hystrix:
    enabled: true
security:
  oauth2:
    resource:
      token-info-uri: http://localhost:8110/oauth/check_token
    client:
      client-id: demo
      client-secret: demo
      access-token-uri: http://localhost:8110/oauth/token
      user-authorization-uri: http://localhost:8110/oauth/authorize
  basic:
    enabled: false